include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: ignore
    unused_local_variable: ignore
    unused_import: ignore
    unused_field: ignore

linter:
  rules:
    avoid_unnecessary_containers: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false