include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: ignore
    unused_local_variable: ignore
    unused_import: ignore
    unused_field: ignore

linter:
  rules:
    avoid_unnecessary_containers: false
    prefer_const_constructors: false