name: fall_24_flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  neumorphic_ui: ^1.0.1
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
